/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountItemParamsAccountItemItems'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountItemParamsAccountItemItems'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.AccountItemParamsAccountItem = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.AccountItemParamsAccountItemItems);
  }
}(this, function(ApiClient, AccountItemParamsAccountItemItems) {
  'use strict';




  /**
   * The AccountItemParamsAccountItem model module.
   * @module model/AccountItemParamsAccountItem
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>AccountItemParamsAccountItem</code>.
   * @alias module:model/AccountItemParamsAccountItem
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>AccountItemParamsAccountItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountItemParamsAccountItem} obj Optional instance to populate.
   * @return {module:model/AccountItemParamsAccountItem} The populated <code>AccountItemParamsAccountItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('shortcut')) {
        obj['shortcut'] = ApiClient.convertToType(data['shortcut'], 'String');
      }
      if (data.hasOwnProperty('shortcut_num')) {
        obj['shortcut_num'] = ApiClient.convertToType(data['shortcut_num'], 'String');
      }
      if (data.hasOwnProperty('tax_name')) {
        obj['tax_name'] = ApiClient.convertToType(data['tax_name'], 'String');
      }
      if (data.hasOwnProperty('group_name')) {
        obj['group_name'] = ApiClient.convertToType(data['group_name'], 'String');
      }
      if (data.hasOwnProperty('account_category')) {
        obj['account_category'] = ApiClient.convertToType(data['account_category'], 'String');
      }
      if (data.hasOwnProperty('corresponding_income_name')) {
        obj['corresponding_income_name'] = ApiClient.convertToType(data['corresponding_income_name'], 'String');
      }
      if (data.hasOwnProperty('corresponding_expense_name')) {
        obj['corresponding_expense_name'] = ApiClient.convertToType(data['corresponding_expense_name'], 'String');
      }
      if (data.hasOwnProperty('accumulated_dep_account_item_name')) {
        obj['accumulated_dep_account_item_name'] = ApiClient.convertToType(data['accumulated_dep_account_item_name'], 'String');
      }
      if (data.hasOwnProperty('searchable')) {
        obj['searchable'] = ApiClient.convertToType(data['searchable'], 'Number');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [AccountItemParamsAccountItemItems]);
      }
      if (data.hasOwnProperty('partners')) {
        obj['partners'] = ApiClient.convertToType(data['partners'], [AccountItemParamsAccountItemItems]);
      }
    }
    return obj;
  }

  /**
   * 勘定科目名 (30文字以内)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ショートカット1 (20文字以内)
   * @member {String} shortcut
   */
  exports.prototype['shortcut'] = undefined;
  /**
   * ショートカット2(勘定科目コード)(20文字以内)
   * @member {String} shortcut_num
   */
  exports.prototype['shortcut_num'] = undefined;
  /**
   * 税区分
   * @member {String} tax_name
   */
  exports.prototype['tax_name'] = undefined;
  /**
   * 決算書表示名
   * @member {String} group_name
   */
  exports.prototype['group_name'] = undefined;
  /**
   * 勘定科目カテゴリー
   * @member {String} account_category
   */
  exports.prototype['account_category'] = undefined;
  /**
   * 収入取引相手勘定科目
   * @member {String} corresponding_income_name
   */
  exports.prototype['corresponding_income_name'] = undefined;
  /**
   * 支出取引相手勘定科目
   * @member {String} corresponding_expense_name
   */
  exports.prototype['corresponding_expense_name'] = undefined;
  /**
   * 減価償却累計額勘定科目
   * @member {String} accumulated_dep_account_item_name
   */
  exports.prototype['accumulated_dep_account_item_name'] = undefined;
  /**
   * 検索可能:2, 検索不可：3
   * @member {Number} searchable
   */
  exports.prototype['searchable'] = undefined;
  /**
   * 品目
   * @member {Array.<module:model/AccountItemParamsAccountItemItems>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * 取引先
   * @member {Array.<module:model/AccountItemParamsAccountItemItems>} partners
   */
  exports.prototype['partners'] = undefined;



  return exports;
}));


