/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApprovalRequestRequestItems'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApprovalRequestRequestItems'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ApprovalRequest = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.ApprovalRequestRequestItems);
  }
}(this, function(ApiClient, ApprovalRequestRequestItems) {
  'use strict';




  /**
   * The ApprovalRequest model module.
   * @module model/ApprovalRequest
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>ApprovalRequest</code>.
   * @alias module:model/ApprovalRequest
   * @class
   * @param id {Number} その他申請ID
   * @param companyId {Number} 事業所ID
   * @param issueDate {String} 申請日 (yyyy-mm-dd)
   * @param title {String} 申請タイトル
   * @param applicantId {Number} 申請者ID
   * @param approverId {Number} 承認者ID
   * @param applicationNumber {String} 申請No.
   * @param status {module:model/ApprovalRequest.StatusEnum} 申請ステータス
   * @param requestItems {Array.<module:model/ApprovalRequestRequestItems>} その他申請の項目一覧（配列）
   */
  var exports = function(id, companyId, issueDate, title, applicantId, approverId, applicationNumber, status, requestItems) {
    var _this = this;

    _this['id'] = id;
    _this['company_id'] = companyId;
    _this['issue_date'] = issueDate;
    _this['title'] = title;
    _this['applicant_id'] = applicantId;
    _this['approver_id'] = approverId;
    _this['application_number'] = applicationNumber;
    _this['status'] = status;
    _this['request_items'] = requestItems;
  };

  /**
   * Constructs a <code>ApprovalRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApprovalRequest} obj Optional instance to populate.
   * @return {module:model/ApprovalRequest} The populated <code>ApprovalRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('company_id')) {
        obj['company_id'] = ApiClient.convertToType(data['company_id'], 'Number');
      }
      if (data.hasOwnProperty('issue_date')) {
        obj['issue_date'] = ApiClient.convertToType(data['issue_date'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('applicant_id')) {
        obj['applicant_id'] = ApiClient.convertToType(data['applicant_id'], 'Number');
      }
      if (data.hasOwnProperty('approver_id')) {
        obj['approver_id'] = ApiClient.convertToType(data['approver_id'], 'Number');
      }
      if (data.hasOwnProperty('application_number')) {
        obj['application_number'] = ApiClient.convertToType(data['application_number'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('request_items')) {
        obj['request_items'] = ApiClient.convertToType(data['request_items'], [ApprovalRequestRequestItems]);
      }
    }
    return obj;
  }

  /**
   * その他申請ID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 事業所ID
   * @member {Number} company_id
   */
  exports.prototype['company_id'] = undefined;
  /**
   * 申請日 (yyyy-mm-dd)
   * @member {String} issue_date
   */
  exports.prototype['issue_date'] = undefined;
  /**
   * 申請タイトル
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * 申請者ID
   * @member {Number} applicant_id
   */
  exports.prototype['applicant_id'] = undefined;
  /**
   * 承認者ID
   * @member {Number} approver_id
   */
  exports.prototype['approver_id'] = undefined;
  /**
   * 申請No.
   * @member {String} application_number
   */
  exports.prototype['application_number'] = undefined;
  /**
   * 申請ステータス
   * @member {module:model/ApprovalRequest.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * その他申請の項目一覧（配列）
   * @member {Array.<module:model/ApprovalRequestRequestItems>} request_items
   */
  exports.prototype['request_items'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "draft"
     * @const
     */
    "draft": "draft"  };


  return exports;
}));


