/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.BanksIndexResponseBanks = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BanksIndexResponseBanks model module.
   * @module model/BanksIndexResponseBanks
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>BanksIndexResponseBanks</code>.
   * @alias module:model/BanksIndexResponseBanks
   * @class
   * @param id {Number} 連携サービスID
   */
  var exports = function(id) {
    var _this = this;

    _this['id'] = id;


  };

  /**
   * Constructs a <code>BanksIndexResponseBanks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BanksIndexResponseBanks} obj Optional instance to populate.
   * @return {module:model/BanksIndexResponseBanks} The populated <code>BanksIndexResponseBanks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * 連携サービスID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 連携サービス名
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 連携サービス種別: (銀行口座: bank_account, クレジットカード: credit_card, 現金: wallet)
   * @member {module:model/BanksIndexResponseBanks.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "bank_account"
     * @const
     */
    "bank_account": "bank_account",
    /**
     * value: "credit_card"
     * @const
     */
    "credit_card": "credit_card",
    /**
     * value: "wallet"
     * @const
     */
    "wallet": "wallet"  };


  return exports;
}));


