/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BanksIndexResponseBanks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BanksIndexResponseBanks'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.BanksIndexResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.BanksIndexResponseBanks);
  }
}(this, function(ApiClient, BanksIndexResponseBanks) {
  'use strict';




  /**
   * The BanksIndexResponse model module.
   * @module model/BanksIndexResponse
   * @version v1.0
   */

  /**
   * Constructs a new <code>BanksIndexResponse</code>.
   * @alias module:model/BanksIndexResponse
   * @class
   * @param banks {Array.<module:model/BanksIndexResponseBanks>} 
   */
  var exports = function(banks) {
    var _this = this;

    _this['banks'] = banks;
  };

  /**
   * Constructs a <code>BanksIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BanksIndexResponse} obj Optional instance to populate.
   * @return {module:model/BanksIndexResponse} The populated <code>BanksIndexResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('banks')) {
        obj['banks'] = ApiClient.convertToType(data['banks'], [BanksIndexResponseBanks]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/BanksIndexResponseBanks>} banks
   */
  exports.prototype['banks'] = undefined;



  return exports;
}));


