/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.DealsDetails = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DealsDetails model module.
   * @module model/DealsDetails
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>DealsDetails</code>.
   * @alias module:model/DealsDetails
   * @class
   * @param id {Number} 取引行ID
   * @param accountItemId {Number} 勘定科目ID
   * @param taxCode {Number} 税区分コード
   * @param amount {Number} 取引金額
   * @param vat {Number} 消費税額
   * @param entrySide {module:model/DealsDetails.EntrySideEnum} 貸借（貸方: credit, 借方: debit）
   */
  var exports = function(id, accountItemId, taxCode, amount, vat, entrySide) {
    var _this = this;

    _this['id'] = id;
    _this['account_item_id'] = accountItemId;

    _this['tax_code'] = taxCode;

    _this['amount'] = amount;
    _this['vat'] = vat;

    _this['entry_side'] = entrySide;
  };

  /**
   * Constructs a <code>DealsDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DealsDetails} obj Optional instance to populate.
   * @return {module:model/DealsDetails} The populated <code>DealsDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('account_item_id')) {
        obj['account_item_id'] = ApiClient.convertToType(data['account_item_id'], 'Number');
      }
      if (data.hasOwnProperty('tax_id')) {
        obj['tax_id'] = ApiClient.convertToType(data['tax_id'], 'Number');
      }
      if (data.hasOwnProperty('tax_code')) {
        obj['tax_code'] = ApiClient.convertToType(data['tax_code'], 'Number');
      }
      if (data.hasOwnProperty('tag_ids')) {
        obj['tag_ids'] = ApiClient.convertToType(data['tag_ids'], ['Number']);
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('vat')) {
        obj['vat'] = ApiClient.convertToType(data['vat'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('entry_side')) {
        obj['entry_side'] = ApiClient.convertToType(data['entry_side'], 'String');
      }
    }
    return obj;
  }

  /**
   * 取引行ID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 勘定科目ID
   * @member {Number} account_item_id
   */
  exports.prototype['account_item_id'] = undefined;
  /**
   * 税区分ID（廃止予定）
   * @member {Number} tax_id
   */
  exports.prototype['tax_id'] = undefined;
  /**
   * 税区分コード
   * @member {Number} tax_code
   */
  exports.prototype['tax_code'] = undefined;
  /**
   * メモタグID
   * @member {Array.<Number>} tag_ids
   */
  exports.prototype['tag_ids'] = undefined;
  /**
   * 取引金額
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * 消費税額
   * @member {Number} vat
   */
  exports.prototype['vat'] = undefined;
  /**
   * 備考
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * 貸借（貸方: credit, 借方: debit）
   * @member {module:model/DealsDetails.EntrySideEnum} entry_side
   */
  exports.prototype['entry_side'] = undefined;


  /**
   * Allowed values for the <code>entry_side</code> property.
   * @enum {String}
   * @readonly
   */
  exports.EntrySideEnum = {
    /**
     * value: "credit"
     * @const
     */
    "credit": "credit",
    /**
     * value: "debit"
     * @const
     */
    "debit": "debit"  };


  return exports;
}));


