/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ExpenseApplicationLineTemplate = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExpenseApplicationLineTemplate model module.
   * @module model/ExpenseApplicationLineTemplate
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>ExpenseApplicationLineTemplate</code>.
   * @alias module:model/ExpenseApplicationLineTemplate
   * @class
   * @param id {Number} 経費科目ID
   * @param name {String} 経費科目名
   * @param accountItemName {String} 勘定科目名
   * @param taxName {String} 税区分名
   */
  var exports = function(id, name, accountItemName, taxName) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['account_item_name'] = accountItemName;
    _this['tax_name'] = taxName;


  };

  /**
   * Constructs a <code>ExpenseApplicationLineTemplate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExpenseApplicationLineTemplate} obj Optional instance to populate.
   * @return {module:model/ExpenseApplicationLineTemplate} The populated <code>ExpenseApplicationLineTemplate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('account_item_name')) {
        obj['account_item_name'] = ApiClient.convertToType(data['account_item_name'], 'String');
      }
      if (data.hasOwnProperty('tax_name')) {
        obj['tax_name'] = ApiClient.convertToType(data['tax_name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('line_description')) {
        obj['line_description'] = ApiClient.convertToType(data['line_description'], 'String');
      }
    }
    return obj;
  }

  /**
   * 経費科目ID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 経費科目名
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 勘定科目名
   * @member {String} account_item_name
   */
  exports.prototype['account_item_name'] = undefined;
  /**
   * 税区分名
   * @member {String} tax_name
   */
  exports.prototype['tax_name'] = undefined;
  /**
   * 経費科目の説明
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * 内容の補足
   * @member {String} line_description
   */
  exports.prototype['line_description'] = undefined;



  return exports;
}));


