/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExpenseApplicationLineTemplate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExpenseApplicationLineTemplate'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ExpenseApplicationLineTemplatesIndexResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.ExpenseApplicationLineTemplate);
  }
}(this, function(ApiClient, ExpenseApplicationLineTemplate) {
  'use strict';




  /**
   * The ExpenseApplicationLineTemplatesIndexResponse model module.
   * @module model/ExpenseApplicationLineTemplatesIndexResponse
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>ExpenseApplicationLineTemplatesIndexResponse</code>.
   * @alias module:model/ExpenseApplicationLineTemplatesIndexResponse
   * @class
   * @param expenseApplicationLineTemplates {Array.<module:model/ExpenseApplicationLineTemplate>} 
   */
  var exports = function(expenseApplicationLineTemplates) {
    var _this = this;

    _this['expense_application_line_templates'] = expenseApplicationLineTemplates;
  };

  /**
   * Constructs a <code>ExpenseApplicationLineTemplatesIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExpenseApplicationLineTemplatesIndexResponse} obj Optional instance to populate.
   * @return {module:model/ExpenseApplicationLineTemplatesIndexResponse} The populated <code>ExpenseApplicationLineTemplatesIndexResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('expense_application_line_templates')) {
        obj['expense_application_line_templates'] = ApiClient.convertToType(data['expense_application_line_templates'], [ExpenseApplicationLineTemplate]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ExpenseApplicationLineTemplate>} expense_application_line_templates
   */
  exports.prototype['expense_application_line_templates'] = undefined;



  return exports;
}));


