/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ExpenseApplicationsidExpenseApplicationLines = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExpenseApplicationsidExpenseApplicationLines model module.
   * @module model/ExpenseApplicationsidExpenseApplicationLines
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>ExpenseApplicationsidExpenseApplicationLines</code>.
   * @alias module:model/ExpenseApplicationsidExpenseApplicationLines
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ExpenseApplicationsidExpenseApplicationLines</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExpenseApplicationsidExpenseApplicationLines} obj Optional instance to populate.
   * @return {module:model/ExpenseApplicationsidExpenseApplicationLines} The populated <code>ExpenseApplicationsidExpenseApplicationLines</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('transaction_date')) {
        obj['transaction_date'] = ApiClient.convertToType(data['transaction_date'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('expense_application_line_template_id')) {
        obj['expense_application_line_template_id'] = ApiClient.convertToType(data['expense_application_line_template_id'], 'Number');
      }
      if (data.hasOwnProperty('receipt_id')) {
        obj['receipt_id'] = ApiClient.convertToType(data['receipt_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 経費申請の項目行ID: 既存項目行を更新する場合に指定します。IDを指定しない項目行は、新規行として扱われ追加されます。また、expense_application_linesに含まれない既存の項目行は削除されます。更新後も残したい行は、必ず経費申請の項目行IDを指定してexpense_application_linesに含めてください。
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 日付 (yyyy-mm-dd)
   * @member {String} transaction_date
   */
  exports.prototype['transaction_date'] = undefined;
  /**
   * 内容
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * 金額
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * 経費科目ID
   * @member {Number} expense_application_line_template_id
   */
  exports.prototype['expense_application_line_template_id'] = undefined;
  /**
   * 証憑ID
   * @member {Number} receipt_id
   */
  exports.prototype['receipt_id'] = undefined;



  return exports;
}));


