/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Invoice'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Invoice'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.InvoicesResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.Invoice);
  }
}(this, function(ApiClient, Invoice) {
  'use strict';




  /**
   * The InvoicesResponse model module.
   * @module model/InvoicesResponse
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>InvoicesResponse</code>.
   * @alias module:model/InvoicesResponse
   * @class
   * @param invoice {module:model/Invoice} 
   */
  var exports = function(invoice) {
    var _this = this;

    _this['invoice'] = invoice;
  };

  /**
   * Constructs a <code>InvoicesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoicesResponse} obj Optional instance to populate.
   * @return {module:model/InvoicesResponse} The populated <code>InvoicesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('invoice')) {
        obj['invoice'] = Invoice.constructFromObject(data['invoice']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Invoice} invoice
   */
  exports.prototype['invoice'] = undefined;



  return exports;
}));


