/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ItemsCreateResponseItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ItemsCreateResponseItem'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ItemsCreateResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.ItemsCreateResponseItem);
  }
}(this, function(ApiClient, ItemsCreateResponseItem) {
  'use strict';




  /**
   * The ItemsCreateResponse model module.
   * @module model/ItemsCreateResponse
   * @version v1.0
   */

  /**
   * Constructs a new <code>ItemsCreateResponse</code>.
   * @alias module:model/ItemsCreateResponse
   * @class
   * @param item {module:model/ItemsCreateResponseItem} 
   */
  var exports = function(item) {
    var _this = this;

    _this['item'] = item;
  };

  /**
   * Constructs a <code>ItemsCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ItemsCreateResponse} obj Optional instance to populate.
   * @return {module:model/ItemsCreateResponse} The populated <code>ItemsCreateResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('item')) {
        obj['item'] = ItemsCreateResponseItem.constructFromObject(data['item']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ItemsCreateResponseItem} item
   */
  exports.prototype['item'] = undefined;



  return exports;
}));


