/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ItemsIndexResponseItems'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ItemsIndexResponseItems'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ItemsIndexResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.ItemsIndexResponseItems);
  }
}(this, function(ApiClient, ItemsIndexResponseItems) {
  'use strict';




  /**
   * The ItemsIndexResponse model module.
   * @module model/ItemsIndexResponse
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>ItemsIndexResponse</code>.
   * @alias module:model/ItemsIndexResponse
   * @class
   * @param items {Array.<module:model/ItemsIndexResponseItems>} 
   */
  var exports = function(items) {
    var _this = this;

    _this['items'] = items;
  };

  /**
   * Constructs a <code>ItemsIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ItemsIndexResponse} obj Optional instance to populate.
   * @return {module:model/ItemsIndexResponse} The populated <code>ItemsIndexResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [ItemsIndexResponseItems]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ItemsIndexResponseItems>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


