/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.JournalsStatusResponseJournals = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JournalsStatusResponseJournals model module.
   * @module model/JournalsStatusResponseJournals
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>JournalsStatusResponseJournals</code>.
   * @alias module:model/JournalsStatusResponseJournals
   * @class
   * @param id {Number} 受け付けID
   * @param companyId {Number} 事業所ID
   * @param downloadType {module:model/JournalsStatusResponseJournals.DownloadTypeEnum} ダウンロード形式
   * @param status {module:model/JournalsStatusResponseJournals.StatusEnum} 事業所ID
   * @param startDate {String} 取得開始日 (yyyy-mm-dd)
   * @param endDate {String} 取得終了日 (yyyy-mm-dd)
   * @param visibleTags {Array.<module:model/JournalsStatusResponseJournals.VisibleTagsEnum>} 
   */
  var exports = function(id, companyId, downloadType, status, startDate, endDate, visibleTags) {
    var _this = this;

    _this['id'] = id;
    _this['company_id'] = companyId;
    _this['download_type'] = downloadType;
    _this['status'] = status;
    _this['start_date'] = startDate;
    _this['end_date'] = endDate;
    _this['visible_tags'] = visibleTags;

  };

  /**
   * Constructs a <code>JournalsStatusResponseJournals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JournalsStatusResponseJournals} obj Optional instance to populate.
   * @return {module:model/JournalsStatusResponseJournals} The populated <code>JournalsStatusResponseJournals</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('company_id')) {
        obj['company_id'] = ApiClient.convertToType(data['company_id'], 'Number');
      }
      if (data.hasOwnProperty('download_type')) {
        obj['download_type'] = ApiClient.convertToType(data['download_type'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('start_date')) {
        obj['start_date'] = ApiClient.convertToType(data['start_date'], 'String');
      }
      if (data.hasOwnProperty('end_date')) {
        obj['end_date'] = ApiClient.convertToType(data['end_date'], 'String');
      }
      if (data.hasOwnProperty('visible_tags')) {
        obj['visible_tags'] = ApiClient.convertToType(data['visible_tags'], ['String']);
      }
      if (data.hasOwnProperty('download_url')) {
        obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
      }
    }
    return obj;
  }

  /**
   * 受け付けID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 事業所ID
   * @member {Number} company_id
   */
  exports.prototype['company_id'] = undefined;
  /**
   * ダウンロード形式
   * @member {module:model/JournalsStatusResponseJournals.DownloadTypeEnum} download_type
   */
  exports.prototype['download_type'] = undefined;
  /**
   * 事業所ID
   * @member {module:model/JournalsStatusResponseJournals.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * 取得開始日 (yyyy-mm-dd)
   * @member {String} start_date
   */
  exports.prototype['start_date'] = undefined;
  /**
   * 取得終了日 (yyyy-mm-dd)
   * @member {String} end_date
   */
  exports.prototype['end_date'] = undefined;
  /**
   * @member {Array.<module:model/JournalsStatusResponseJournals.VisibleTagsEnum>} visible_tags
   */
  exports.prototype['visible_tags'] = undefined;
  /**
   * ダウンロードURL
   * @member {String} download_url
   */
  exports.prototype['download_url'] = undefined;


  /**
   * Allowed values for the <code>download_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DownloadTypeEnum = {
    /**
     * value: "csv"
     * @const
     */
    "csv": "csv",
    /**
     * value: "generic"
     * @const
     */
    "generic": "generic",
    /**
     * value: "pdf"
     * @const
     */
    "pdf": "pdf"  };

  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "enqueued"
     * @const
     */
    "enqueued": "enqueued",
    /**
     * value: "working"
     * @const
     */
    "working": "working",
    /**
     * value: "uploaded"
     * @const
     */
    "uploaded": "uploaded",
    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"  };

  /**
   * Allowed values for the <code>visibleTags</code> property.
   * @enum {String}
   * @readonly
   */
  exports.VisibleTagsEnum = {
    /**
     * value: "partner"
     * @const
     */
    "partner": "partner",
    /**
     * value: "item"
     * @const
     */
    "item": "item",
    /**
     * value: "tag"
     * @const
     */
    "tag": "tag",
    /**
     * value: "section"
     * @const
     */
    "section": "section",
    /**
     * value: "description"
     * @const
     */
    "description": "description",
    /**
     * value: "wallet_txn_description"
     * @const
     */
    "wallet_txn_description": "wallet_txn_description",
    /**
     * value: "all"
     * @const
     */
    "all": "all"  };


  return exports;
}));


