/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/JournalsStatusResponseJournals'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JournalsStatusResponseJournals'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.JournalsStatusResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.JournalsStatusResponseJournals);
  }
}(this, function(ApiClient, JournalsStatusResponseJournals) {
  'use strict';




  /**
   * The JournalsStatusResponse model module.
   * @module model/JournalsStatusResponse
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>JournalsStatusResponse</code>.
   * @alias module:model/JournalsStatusResponse
   * @class
   * @param journals {module:model/JournalsStatusResponseJournals} 
   */
  var exports = function(journals) {
    var _this = this;

    _this['journals'] = journals;
  };

  /**
   * Constructs a <code>JournalsStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JournalsStatusResponse} obj Optional instance to populate.
   * @return {module:model/JournalsStatusResponse} The populated <code>JournalsStatusResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('journals')) {
        obj['journals'] = JournalsStatusResponseJournals.constructFromObject(data['journals']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/JournalsStatusResponseJournals} journals
   */
  exports.prototype['journals'] = undefined;



  return exports;
}));


