/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PartnerParamsAddressAttributes', 'model/PartnerParamsPartnerBankAccountAttributes', 'model/PartnerParamsPartnerDocSettingAttributes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PartnerParamsAddressAttributes'), require('./PartnerParamsPartnerBankAccountAttributes'), require('./PartnerParamsPartnerDocSettingAttributes'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.PartnerParams = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.PartnerParamsAddressAttributes, root.FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes, root.FreeeAccountingClient.PartnerParamsPartnerDocSettingAttributes);
  }
}(this, function(ApiClient, PartnerParamsAddressAttributes, PartnerParamsPartnerBankAccountAttributes, PartnerParamsPartnerDocSettingAttributes) {
  'use strict';




  /**
   * The PartnerParams model module.
   * @module model/PartnerParams
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>PartnerParams</code>.
   * @alias module:model/PartnerParams
   * @class
   * @param companyId {Number} 事業所ID
   * @param name {String} 取引先名 (30文字以内)
   */
  var exports = function(companyId, name) {
    var _this = this;

    _this['company_id'] = companyId;
    _this['name'] = name;











  };

  /**
   * Constructs a <code>PartnerParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartnerParams} obj Optional instance to populate.
   * @return {module:model/PartnerParams} The populated <code>PartnerParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('company_id')) {
        obj['company_id'] = ApiClient.convertToType(data['company_id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('shortcut1')) {
        obj['shortcut1'] = ApiClient.convertToType(data['shortcut1'], 'String');
      }
      if (data.hasOwnProperty('shortcut2')) {
        obj['shortcut2'] = ApiClient.convertToType(data['shortcut2'], 'String');
      }
      if (data.hasOwnProperty('long_name')) {
        obj['long_name'] = ApiClient.convertToType(data['long_name'], 'String');
      }
      if (data.hasOwnProperty('name_kana')) {
        obj['name_kana'] = ApiClient.convertToType(data['name_kana'], 'String');
      }
      if (data.hasOwnProperty('default_title')) {
        obj['default_title'] = ApiClient.convertToType(data['default_title'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('contact_name')) {
        obj['contact_name'] = ApiClient.convertToType(data['contact_name'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('address_attributes')) {
        obj['address_attributes'] = PartnerParamsAddressAttributes.constructFromObject(data['address_attributes']);
      }
      if (data.hasOwnProperty('partner_doc_setting_attributes')) {
        obj['partner_doc_setting_attributes'] = PartnerParamsPartnerDocSettingAttributes.constructFromObject(data['partner_doc_setting_attributes']);
      }
      if (data.hasOwnProperty('partner_bank_account_attributes')) {
        obj['partner_bank_account_attributes'] = PartnerParamsPartnerBankAccountAttributes.constructFromObject(data['partner_bank_account_attributes']);
      }
    }
    return obj;
  }

  /**
   * 事業所ID
   * @member {Number} company_id
   */
  exports.prototype['company_id'] = undefined;
  /**
   * 取引先名 (30文字以内)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ショートカット１ (20文字以内)
   * @member {String} shortcut1
   */
  exports.prototype['shortcut1'] = undefined;
  /**
   * ショートカット２ (20文字以内)
   * @member {String} shortcut2
   */
  exports.prototype['shortcut2'] = undefined;
  /**
   * 正式名称（255文字以内）
   * @member {String} long_name
   */
  exports.prototype['long_name'] = undefined;
  /**
   * カナ名称（255文字以内）
   * @member {String} name_kana
   */
  exports.prototype['name_kana'] = undefined;
  /**
   * 敬称（御中、様、(空白)の3つから選択）
   * @member {module:model/PartnerParams.DefaultTitleEnum} default_title
   */
  exports.prototype['default_title'] = undefined;
  /**
   * 電話番号
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * 営業担当者名
   * @member {String} contact_name
   */
  exports.prototype['contact_name'] = undefined;
  /**
   * 営業担当者 メールアドレス
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {module:model/PartnerParamsAddressAttributes} address_attributes
   */
  exports.prototype['address_attributes'] = undefined;
  /**
   * @member {module:model/PartnerParamsPartnerDocSettingAttributes} partner_doc_setting_attributes
   */
  exports.prototype['partner_doc_setting_attributes'] = undefined;
  /**
   * @member {module:model/PartnerParamsPartnerBankAccountAttributes} partner_bank_account_attributes
   */
  exports.prototype['partner_bank_account_attributes'] = undefined;


  /**
   * Allowed values for the <code>default_title</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DefaultTitleEnum = {
    /**
     * value: ""
     * @const
     */
    "empty": "",
    /**
     * value: "(空白)"
     * @const
     */
    "(空白)": "(空白)",
    /**
     * value: "御中"
     * @const
     */
    "御中": "御中",
    /**
     * value: "様"
     * @const
     */
    "様": "様"  };


  return exports;
}));


