/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.PartnerParamsPartnerDocSettingAttributes = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PartnerParamsPartnerDocSettingAttributes model module.
   * @module model/PartnerParamsPartnerDocSettingAttributes
   * @version v1.0
   */

  /**
   * Constructs a new <code>PartnerParamsPartnerDocSettingAttributes</code>.
   * @alias module:model/PartnerParamsPartnerDocSettingAttributes
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PartnerParamsPartnerDocSettingAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartnerParamsPartnerDocSettingAttributes} obj Optional instance to populate.
   * @return {module:model/PartnerParamsPartnerDocSettingAttributes} The populated <code>PartnerParamsPartnerDocSettingAttributes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sending_method')) {
        obj['sending_method'] = ApiClient.convertToType(data['sending_method'], 'String');
      }
    }
    return obj;
  }

  /**
   * 請求書送付方法(mail:メール、posting:郵送、mail_and_posting:メールと郵送)
   * @member {String} sending_method
   */
  exports.prototype['sending_method'] = undefined;



  return exports;
}));


