/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.PartnersResponse = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PartnersResponse model module.
   * @module model/PartnersResponse
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>PartnersResponse</code>.
   * @alias module:model/PartnersResponse
   * @class
   * @param partner {Object} 
   */
  var exports = function(partner) {
    var _this = this;

    _this['partner'] = partner;
  };

  /**
   * Constructs a <code>PartnersResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartnersResponse} obj Optional instance to populate.
   * @return {module:model/PartnersResponse} The populated <code>PartnersResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('partner')) {
        obj['partner'] = ApiClient.convertToType(data['partner'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Object} partner
   */
  exports.prototype['partner'] = undefined;



  return exports;
}));


