/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.SectionParams = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SectionParams model module.
   * @module model/SectionParams
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>SectionParams</code>.
   * @alias module:model/SectionParams
   * @class
   * @param companyId {Number} 事業所ID
   * @param name {String} 部門名 (30文字以内)
   */
  var exports = function(companyId, name) {
    var _this = this;

    _this['company_id'] = companyId;
    _this['name'] = name;



  };

  /**
   * Constructs a <code>SectionParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SectionParams} obj Optional instance to populate.
   * @return {module:model/SectionParams} The populated <code>SectionParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('company_id')) {
        obj['company_id'] = ApiClient.convertToType(data['company_id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('shortcut1')) {
        obj['shortcut1'] = ApiClient.convertToType(data['shortcut1'], 'String');
      }
      if (data.hasOwnProperty('shortcut2')) {
        obj['shortcut2'] = ApiClient.convertToType(data['shortcut2'], 'String');
      }
      if (data.hasOwnProperty('parent_id')) {
        obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 事業所ID
   * @member {Number} company_id
   */
  exports.prototype['company_id'] = undefined;
  /**
   * 部門名 (30文字以内)
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * ショートカット１ (20文字以内)
   * @member {String} shortcut1
   */
  exports.prototype['shortcut1'] = undefined;
  /**
   * ショートカット２ (20文字以内)
   * @member {String} shortcut2
   */
  exports.prototype['shortcut2'] = undefined;
  /**
   * 親部門ID (ビジネスプラン以上)
   * @member {Number} parent_id
   */
  exports.prototype['parent_id'] = undefined;



  return exports;
}));


