/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SelectablesIndexResponseDefaultTaxTaxRate5', 'model/SelectablesIndexResponseDefaultTaxTaxRate8'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SelectablesIndexResponseDefaultTaxTaxRate5'), require('./SelectablesIndexResponseDefaultTaxTaxRate8'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.SelectablesIndexResponseDefaultTax = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.SelectablesIndexResponseDefaultTaxTaxRate5, root.FreeeAccountingClient.SelectablesIndexResponseDefaultTaxTaxRate8);
  }
}(this, function(ApiClient, SelectablesIndexResponseDefaultTaxTaxRate5, SelectablesIndexResponseDefaultTaxTaxRate8) {
  'use strict';




  /**
   * The SelectablesIndexResponseDefaultTax model module.
   * @module model/SelectablesIndexResponseDefaultTax
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>SelectablesIndexResponseDefaultTax</code>.
   * @alias module:model/SelectablesIndexResponseDefaultTax
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SelectablesIndexResponseDefaultTax</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SelectablesIndexResponseDefaultTax} obj Optional instance to populate.
   * @return {module:model/SelectablesIndexResponseDefaultTax} The populated <code>SelectablesIndexResponseDefaultTax</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tax_rate_5')) {
        obj['tax_rate_5'] = SelectablesIndexResponseDefaultTaxTaxRate5.constructFromObject(data['tax_rate_5']);
      }
      if (data.hasOwnProperty('tax_rate_8')) {
        obj['tax_rate_8'] = SelectablesIndexResponseDefaultTaxTaxRate8.constructFromObject(data['tax_rate_8']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SelectablesIndexResponseDefaultTaxTaxRate5} tax_rate_5
   */
  exports.prototype['tax_rate_5'] = undefined;
  /**
   * @member {module:model/SelectablesIndexResponseDefaultTaxTaxRate8} tax_rate_8
   */
  exports.prototype['tax_rate_8'] = undefined;



  return exports;
}));


