/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tag'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.TagsIndexResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.Tag);
  }
}(this, function(ApiClient, Tag) {
  'use strict';




  /**
   * The TagsIndexResponse model module.
   * @module model/TagsIndexResponse
   * @version v1.0
   */

  /**
   * Constructs a new <code>TagsIndexResponse</code>.
   * @alias module:model/TagsIndexResponse
   * @class
   * @param tags {Array.<module:model/Tag>} 
   */
  var exports = function(tags) {
    var _this = this;

    _this['tags'] = tags;
  };

  /**
   * Constructs a <code>TagsIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagsIndexResponse} obj Optional instance to populate.
   * @return {module:model/TagsIndexResponse} The populated <code>TagsIndexResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Tag>} tags
   */
  exports.prototype['tags'] = undefined;



  return exports;
}));


