/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.TaxesCodesResponseTaxes = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TaxesCodesResponseTaxes model module.
   * @module model/TaxesCodesResponseTaxes
   * @version v0.0.2
   */

  /**
   * Constructs a new <code>TaxesCodesResponseTaxes</code>.
   * @alias module:model/TaxesCodesResponseTaxes
   * @class
   * @param code {Number} 税区分コード
   * @param name {String} 税区分名
   * @param nameJa {String} 税区分名（日本語表示用）
   */
  var exports = function(code, name, nameJa) {
    var _this = this;

    _this['code'] = code;
    _this['name'] = name;
    _this['name_ja'] = nameJa;
  };

  /**
   * Constructs a <code>TaxesCodesResponseTaxes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaxesCodesResponseTaxes} obj Optional instance to populate.
   * @return {module:model/TaxesCodesResponseTaxes} The populated <code>TaxesCodesResponseTaxes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('name_ja')) {
        obj['name_ja'] = ApiClient.convertToType(data['name_ja'], 'String');
      }
    }
    return obj;
  }

  /**
   * 税区分コード
   * @member {Number} code
   */
  exports.prototype['code'] = undefined;
  /**
   * 税区分名
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 税区分名（日本語表示用）
   * @member {String} name_ja
   */
  exports.prototype['name_ja'] = undefined;



  return exports;
}));


