/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TaxesIndexResponseTaxes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TaxesIndexResponseTaxes'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.TaxesIndexResponse = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.TaxesIndexResponseTaxes);
  }
}(this, function(ApiClient, TaxesIndexResponseTaxes) {
  'use strict';




  /**
   * The TaxesIndexResponse model module.
   * @module model/TaxesIndexResponse
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>TaxesIndexResponse</code>.
   * @alias module:model/TaxesIndexResponse
   * @class
   * @param taxes {Array.<module:model/TaxesIndexResponseTaxes>} 
   */
  var exports = function(taxes) {
    var _this = this;

    _this['taxes'] = taxes;
  };

  /**
   * Constructs a <code>TaxesIndexResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaxesIndexResponse} obj Optional instance to populate.
   * @return {module:model/TaxesIndexResponse} The populated <code>TaxesIndexResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('taxes')) {
        obj['taxes'] = ApiClient.convertToType(data['taxes'], [TaxesIndexResponseTaxes]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/TaxesIndexResponseTaxes>} taxes
   */
  exports.prototype['taxes'] = undefined;



  return exports;
}));


