/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UsersMeResponseUserCompanies'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UsersMeResponseUserCompanies'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.UsersMeResponseUser = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.UsersMeResponseUserCompanies);
  }
}(this, function(ApiClient, UsersMeResponseUserCompanies) {
  'use strict';




  /**
   * The UsersMeResponseUser model module.
   * @module model/UsersMeResponseUser
   * @version v1.0
   */

  /**
   * Constructs a new <code>UsersMeResponseUser</code>.
   * @alias module:model/UsersMeResponseUser
   * @class
   * @param id {Number} ユーザーID
   * @param email {String} メールアドレス
   */
  var exports = function(id, email) {
    var _this = this;

    _this['id'] = id;
    _this['email'] = email;

  };

  /**
   * Constructs a <code>UsersMeResponseUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersMeResponseUser} obj Optional instance to populate.
   * @return {module:model/UsersMeResponseUser} The populated <code>UsersMeResponseUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('companies')) {
        obj['companies'] = ApiClient.convertToType(data['companies'], [UsersMeResponseUserCompanies]);
      }
    }
    return obj;
  }

  /**
   * ユーザーID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * メールアドレス
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {Array.<module:model/UsersMeResponseUserCompanies>} companies
   */
  exports.prototype['companies'] = undefined;



  return exports;
}));


