/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.UsersCapability = factory(root.FreeeAccountingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UsersCapability model module.
   * @module model/UsersCapability
   * @version v0.0.1
   */

  /**
   * Constructs a new <code>UsersCapability</code>.
   * @alias module:model/UsersCapability
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>UsersCapability</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersCapability} obj Optional instance to populate.
   * @return {module:model/UsersCapability} The populated <code>UsersCapability</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('read')) {
        obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
      }
      if (data.hasOwnProperty('create')) {
        obj['create'] = ApiClient.convertToType(data['create'], 'Boolean');
      }
      if (data.hasOwnProperty('update')) {
        obj['update'] = ApiClient.convertToType(data['update'], 'Boolean');
      }
      if (data.hasOwnProperty('destroy')) {
        obj['destroy'] = ApiClient.convertToType(data['destroy'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * 閲覧
   * @member {Boolean} read
   */
  exports.prototype['read'] = undefined;
  /**
   * 作成
   * @member {Boolean} create
   */
  exports.prototype['create'] = undefined;
  /**
   * 更新
   * @member {Boolean} update
   */
  exports.prototype['update'] = undefined;
  /**
   * 削除
   * @member {Boolean} destroy
   */
  exports.prototype['destroy'] = undefined;



  return exports;
}));


