/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BadRequestError', 'model/ExpenseApplicationsResponse', 'model/Parameter5', 'model/Parameters7', 'model/Parameters8', 'model/UnauthorizedError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BadRequestError'), require('../model/ExpenseApplicationsResponse'), require('../model/Parameter5'), require('../model/Parameters7'), require('../model/Parameters8'), require('../model/UnauthorizedError'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.ExpenseApplicationsApi = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.BadRequestError, root.FreeeAccountingClient.ExpenseApplicationsResponse, root.FreeeAccountingClient.Parameter5, root.FreeeAccountingClient.Parameters7, root.FreeeAccountingClient.Parameters8, root.FreeeAccountingClient.UnauthorizedError);
  }
}(this, function(ApiClient, BadRequestError, ExpenseApplicationsResponse, Parameter5, Parameters7, Parameters8, UnauthorizedError) {
  'use strict';

  /**
   * ExpenseApplications service.
   * @module api/ExpenseApplicationsApi
   * @version v0.0.2
   */

  /**
   * Constructs a new ExpenseApplicationsApi. 
   * @alias module:api/ExpenseApplicationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createExpenseApplication operation.
     * @callback module:api/ExpenseApplicationsApi~createExpenseApplicationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpenseApplicationsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 経費申請の作成
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/Parameters7} opts.parameters 経費申請の作成
     * @param {module:api/ExpenseApplicationsApi~createExpenseApplicationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExpenseApplicationsResponse}
     */
    this.createExpenseApplication = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['parameters'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = ExpenseApplicationsResponse;

      return this.apiClient.callApi(
        '/expense_applications', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the destroyExpenseApplication operation.
     * @callback module:api/ExpenseApplicationsApi~destroyExpenseApplicationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 経費申請の削除
     * 
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Parameter5} opts.parameter 経費申請の削除
     * @param {module:api/ExpenseApplicationsApi~destroyExpenseApplicationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.destroyExpenseApplication = function(id, opts, callback) {
      opts = opts || {};
      var postBody = opts['parameter'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling destroyExpenseApplication");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/expense_applications/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateExpenseApplication operation.
     * @callback module:api/ExpenseApplicationsApi~updateExpenseApplicationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpenseApplicationsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 経費申請の更新
     * 
     * @param {Number} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Parameters8} opts.parameters 経費申請の更新
     * @param {module:api/ExpenseApplicationsApi~updateExpenseApplicationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExpenseApplicationsResponse}
     */
    this.updateExpenseApplication = function(id, opts, callback) {
      opts = opts || {};
      var postBody = opts['parameters'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateExpenseApplication");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = ExpenseApplicationsResponse;

      return this.apiClient.callApi(
        '/expense_applications/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
