/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BadRequestError', 'model/UnauthorizedError', 'model/UsersCapabilitiesResponse', 'model/UsersMeResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BadRequestError'), require('../model/UnauthorizedError'), require('../model/UsersCapabilitiesResponse'), require('../model/UsersMeResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.FreeeAccountingClient) {
      root.FreeeAccountingClient = {};
    }
    root.FreeeAccountingClient.UsersApi = factory(root.FreeeAccountingClient.ApiClient, root.FreeeAccountingClient.BadRequestError, root.FreeeAccountingClient.UnauthorizedError, root.FreeeAccountingClient.UsersCapabilitiesResponse, root.FreeeAccountingClient.UsersMeResponse);
  }
}(this, function(ApiClient, BadRequestError, UnauthorizedError, UsersCapabilitiesResponse, UsersMeResponse) {
  'use strict';

  /**
   * Users service.
   * @module api/UsersApi
   * @version v1.0
   */

  /**
   * Constructs a new UsersApi. 
   * @alias module:api/UsersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getUsersCapabilities operation.
     * @callback module:api/UsersApi~getUsersCapabilitiesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsersCapabilitiesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ログインユーザの権限の取得
     * 
     * @param {Number} companyId 事業所ID
     * @param {module:api/UsersApi~getUsersCapabilitiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsersCapabilitiesResponse}
     */
    this.getUsersCapabilities = function(companyId, callback) {
      var postBody = null;

      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getUsersCapabilities");
      }


      var pathParams = {
      };
      var queryParams = {
        'company_id': companyId,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = UsersCapabilitiesResponse;

      return this.apiClient.callApi(
        '/users/capabilities', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getUsersMe operation.
     * @callback module:api/UsersApi~getUsersMeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsersMeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ログインユーザ情報の取得
     * 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.companies 取得情報にユーザが所属する事業所一覧を含める
     * @param {module:api/UsersApi~getUsersMeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsersMeResponse}
     */
    this.getUsersMe = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'companies': opts['companies'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json'];
      var returnType = UsersMeResponse;

      return this.apiClient.callApi(
        '/users/me', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
