/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeeAccountingClient);
  }
}(this, function(expect, FreeeAccountingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeeAccountingClient.FiscalYears();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FiscalYears', function() {
    it('should create an instance of FiscalYears', function() {
      // uncomment below and update the code to test FiscalYears
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be.a(FreeeAccountingClient.FiscalYears);
    });

    it('should have the property useIndustryTemplate (base name: "use_industry_template")', function() {
      // uncomment below and update the code to test the property useIndustryTemplate
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property indirectWriteOffMethod (base name: "indirect_write_off_method")', function() {
      // uncomment below and update the code to test the property indirectWriteOffMethod
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "end_date")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property depreciationRecordMethod (base name: "depreciation_record_method")', function() {
      // uncomment below and update the code to test the property depreciationRecordMethod
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property taxMethod (base name: "tax_method")', function() {
      // uncomment below and update the code to test the property taxMethod
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property salesTaxBusinessCode (base name: "sales_tax_business_code")', function() {
      // uncomment below and update the code to test the property salesTaxBusinessCode
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property taxFraction (base name: "tax_fraction")', function() {
      // uncomment below and update the code to test the property taxFraction
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property taxAccountMethod (base name: "tax_account_method")', function() {
      // uncomment below and update the code to test the property taxAccountMethod
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

    it('should have the property returnCode (base name: "return_code")', function() {
      // uncomment below and update the code to test the property returnCode
      //var instance = new FreeeAccountingClient.FiscalYears();
      //expect(instance).to.be();
    });

  });

}));
