/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeeAccountingClient);
  }
}(this, function(expect, FreeeAccountingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeeAccountingClient.Invoice();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Invoice', function() {
    it('should create an instance of Invoice', function() {
      // uncomment below and update the code to test Invoice
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be.a(FreeeAccountingClient.Invoice);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property issueDate (base name: "issue_date")', function() {
      // uncomment below and update the code to test the property issueDate
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "invoice_number")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property dueDate (base name: "due_date")', function() {
      // uncomment below and update the code to test the property dueDate
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "total_amount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property totalVat (base name: "total_vat")', function() {
      // uncomment below and update the code to test the property totalVat
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property subTotal (base name: "sub_total")', function() {
      // uncomment below and update the code to test the property subTotal
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property invoiceStatus (base name: "invoice_status")', function() {
      // uncomment below and update the code to test the property invoiceStatus
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property paymentStatus (base name: "payment_status")', function() {
      // uncomment below and update the code to test the property paymentStatus
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property postingStatus (base name: "posting_status")', function() {
      // uncomment below and update the code to test the property postingStatus
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property paymentType (base name: "payment_type")', function() {
      // uncomment below and update the code to test the property paymentType
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property invoiceLayout (base name: "invoice_layout")', function() {
      // uncomment below and update the code to test the property invoiceLayout
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property taxEntryMethod (base name: "tax_entry_method")', function() {
      // uncomment below and update the code to test the property taxEntryMethod
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

    it('should have the property invoiceContents (base name: "invoice_contents")', function() {
      // uncomment below and update the code to test the property invoiceContents
      //var instance = new FreeeAccountingClient.Invoice();
      //expect(instance).to.be();
    });

  });

}));
