/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeeAccountingClient);
  }
}(this, function(expect, FreeeAccountingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PartnerParamsPartnerBankAccountAttributes', function() {
    it('should create an instance of PartnerParamsPartnerBankAccountAttributes', function() {
      // uncomment below and update the code to test PartnerParamsPartnerBankAccountAttributes
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be.a(FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes);
    });

    it('should have the property bankName (base name: "bank_name")', function() {
      // uncomment below and update the code to test the property bankName
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property bankNameKana (base name: "bank_name_kana")', function() {
      // uncomment below and update the code to test the property bankNameKana
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property bankCode (base name: "bank_code")', function() {
      // uncomment below and update the code to test the property bankCode
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property branchName (base name: "branch_name")', function() {
      // uncomment below and update the code to test the property branchName
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property branchKana (base name: "branch_kana")', function() {
      // uncomment below and update the code to test the property branchKana
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property branchCode (base name: "branch_code")', function() {
      // uncomment below and update the code to test the property branchCode
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property accountType (base name: "account_type")', function() {
      // uncomment below and update the code to test the property accountType
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property accountNumber (base name: "account_number")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property longAccountName (base name: "long_account_name")', function() {
      // uncomment below and update the code to test the property longAccountName
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

    it('should have the property accountName (base name: "account_name")', function() {
      // uncomment below and update the code to test the property accountName
      //var instance = new FreeeAccountingClient.PartnerParamsPartnerBankAccountAttributes();
      //expect(instance).to.be();
    });

  });

}));
