/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeeAccountingClient);
  }
}(this, function(expect, FreeeAccountingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SelectablesIndexResponseAccountCategories', function() {
    it('should create an instance of SelectablesIndexResponseAccountCategories', function() {
      // uncomment below and update the code to test SelectablesIndexResponseAccountCategories
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be.a(FreeeAccountingClient.SelectablesIndexResponseAccountCategories);
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

    it('should have the property orgCode (base name: "org_code")', function() {
      // uncomment below and update the code to test the property orgCode
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

    it('should have the property desc (base name: "desc")', function() {
      // uncomment below and update the code to test the property desc
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

    it('should have the property accountItems (base name: "account_items")', function() {
      // uncomment below and update the code to test the property accountItems
      //var instance = new FreeeAccountingClient.SelectablesIndexResponseAccountCategories();
      //expect(instance).to.be();
    });

  });

}));
