/**
 * freee API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeeAccountingClient);
  }
}(this, function(expect, FreeeAccountingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeeAccountingClient.TaxesCodesResponseTaxes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaxesCodesResponseTaxes', function() {
    it('should create an instance of TaxesCodesResponseTaxes', function() {
      // uncomment below and update the code to test TaxesCodesResponseTaxes
      //var instance = new FreeeAccountingClient.TaxesCodesResponseTaxes();
      //expect(instance).to.be.a(FreeeAccountingClient.TaxesCodesResponseTaxes);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new FreeeAccountingClient.TaxesCodesResponseTaxes();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new FreeeAccountingClient.TaxesCodesResponseTaxes();
      //expect(instance).to.be();
    });

    it('should have the property nameJa (base name: "name_ja")', function() {
      // uncomment below and update the code to test the property nameJa
      //var instance = new FreeeAccountingClient.TaxesCodesResponseTaxes();
      //expect(instance).to.be();
    });

  });

}));
